<a href="https://colab.research.google.com/github/icedumpy/PyTorch-tutorials/blob/main/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Tensors](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

# **Tensor**

* Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

* Tensors are similar to Numpy's ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you're familiar with ndarrays, you'll be right at home with the Tensor API. If not, follow along in this quick API walkthrough.



# Import libraries

In [1]:
import torch
import numpy as np

# Tensor initialization

* Tensors can be initialized in various ways. Take a look at the following examples:

## Directly from data

* Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


## From a NumPy array

* Tensors can be created from NumPy arrays (and vice versa - see **Bridge with NumPy**).



In [3]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


## From another tensor

* The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n{x_rand} \n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
tensor([[0.0483, 0.9258],
        [0.7740, 0.6805]]) 



## With random or constant values

* *shape* is a tuple of tensor dimensions. In the function below, it determines the demintionality of the output tensor.

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor}")

Random Tensor: 
tensor([[0.7791, 0.4190, 0.0527],
        [0.2046, 0.8624, 0.1202]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attributes

* Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operations

* Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively describe [here](https://pytorch.org/docs/stable/torch.html).

* Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're using Colab, allocate a GPU by going to Edit > Notebook Settings (On google colab).

In [7]:
# We move our tensor to the GPU if available
print(tensor.device)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(tensor.device)

cpu
cuda:0


* Try out some of the operations from the list. If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.

## Standard numpy-like indexing and slicing

In [9]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0 # I can assume that I'm using Numpy.
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors

* You can use torch.caat to concatnate a sequence of tensors along a given dimension. See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining op that is subtly different from *torch.cat*

In [19]:
# torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim == axis
print(tensor.shape, t1.shape)

#  torch.stack
t2 = torch.stack([tensor, tensor, tensor], dim=0) # dim == axis
print(tensor.shape, t2.shape)

torch.Size([4, 4]) torch.Size([4, 12])
torch.Size([4, 4]) torch.Size([3, 4, 4])


## Multiplying tensors

* Element-wise product

In [33]:
B = torch.tensor([
    [1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12], 
    [13, 14, 15, 16]
])

print(f"tensor = {tensor}")
print(f"B = {B}\n")

# This computs  the element-wise product
print(f"tensor.mul(tensor)\n{tensor.mul(B)}\n")

# Alternative syntax:
print(f"tensor * B \n {tensor * B}")

tensor = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
B = tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

tensor.mul(tensor)
tensor([[ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.]])

tensor * B 
 tensor([[ 1.,  0.,  3.,  4.],
        [ 5.,  0.,  7.,  8.],
        [ 9.,  0., 11., 12.],
        [13.,  0., 15., 16.]])


* This computes the matrix multiplication between two tensorw

In [37]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n ")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 


## In-place operations

* Operations that have a _ suffix are in-place. For example: **x.copy_(y)**, **x.t_()**, will change x.

* In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [38]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy

* Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

## Tensor to NumPy array

In [43]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


*  A change in the tensor reflects in the NumPy array.

In [44]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [46]:
n = np.ones(5)
t = torch.from_numpy(n)

* Changes in the NumPy array reflects in the tensor.



In [47]:
np.add(n, 1, out=n) # In-place
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
